###Introduction to Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Creating an array
data = np.array([[1,4], [2,5], [3,6]])
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
#Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns = ['col1', 'col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [4]:
data = [[1,4], [2,5], [3,6]]
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns = ['col1', 'col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [5]:
#Creating a DataFrame from a dictionary
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [6]:
dict_states = {'states':states, 'Population':population}
dict_states

{'states': ['California', 'Texas', 'Florida', 'New York'],
 'Population': [39613493, 29730311, 21944577, 19299981]}

In [7]:
df_population = pd.DataFrame(dict_states)
df_population

       states  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

In [8]:
#Creating a DataFrame from a csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
#Show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [10]:
#Show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [11]:
#Show last n rows in a dataframe
df_exams.tail(7)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [12]:
#Getting access to the shape attribute
df_exams.shape

(1000, 8)

In [66]:
pd.set_option('display.max_rows', 10)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
0,female,67,group B,bachelor's degree,standard,none,72,72,74,51,67,86,72.666667
1,female,5,group C,some college,standard,completed,69,90,88,33,5,7,82.333333
2,female,88,group B,master's degree,standard,none,90,95,93,94,88,92,92.666667
3,male,53,group A,associate's degree,free/reduced,none,47,57,44,6,53,50,49.333333
4,male,69,group C,some college,standard,none,76,78,75,99,69,23,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,44,group E,master's degree,standard,completed,88,99,95,11,44,50,94.000000
996,male,96,group C,high school,free/reduced,none,62,55,55,5,96,2,57.333333
997,female,26,group C,high school,free/reduced,completed,59,71,65,96,26,40,65.000000
998,female,92,group D,some college,standard,completed,68,78,77,4,92,51,74.333333
999,female,91,group D,some college,free/reduced,none,77,86,86,21,91,28,83.000000

###Attributes, Methods and Functions

-> Attributes: A value associated with an object (referenced by name using dotted expressions). 
    Ex: df.columns

-> Function: A group of related statements that performs a specific task.
    Ex: python built-in functions: max(); min(); len()

-> Methods: A function which is defined inside a class body.
    Ex: df.head()

####Attributes

In [14]:
#Getting access to the shape attribute
df_exams.shape

(1000, 8)

In [15]:
#Getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [16]:
#Getting access to columns attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [17]:
#Data types of each column
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

####Methods

In [18]:
#Showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [19]:
#Showing the info ofthe dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [20]:
#Describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

####Functions

In [21]:
#Obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [22]:
#Obtaining the highest index of the dataframe
max(df_exams.index)

999

In [23]:
#Obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [24]:
#Obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [25]:
#Rounding the values of the dataset
round(df_exams, 2).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

###Selecting one column

In [26]:
#Select a column with [] (preferred way to select a column)
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [27]:
#Check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [28]:
#Series: attributes and methods
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [29]:
#Select a column with '.'
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [30]:
#Select a column with '.' (pitfalls)
#df_exams.math score -> invalid syntax por causa do espaço

In [31]:
#Select the same column using []
df_exams['math score'].head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

###Selecting two or more columns

In [32]:
#select 2 columns using [[]]
df_exams[['gender', 'math score']].head()

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76

In [33]:
#Check out the data type of the selection
type(df_exams[['gender', 'math score']].head())

pandas.core.frame.DataFrame

In [34]:
#Select 2 or more columns using [[]]
df_exams[['gender', 'math score', 'lunch']].head()

   gender  math score         lunch
0  female          72      standard
1  female          69      standard
2  female          90      standard
3    male          47  free/reduced
4    male          76      standard

In [35]:
#We can't select 2 or more columns with the '.'

Adding a new column

In [36]:
#Adding a new column with a scalar value. Adding new column to dataframe
df_exams['language score'] = 70
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70

In [37]:
#Adding a new column with an array. The dataframe has 1000 rows, so we need to create an array with 1000 elements
#Create an array of 1000 elements
language_score = np.arange(0, 1000)

In [38]:
#Adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [39]:
#Create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size = 1000)

In [40]:
#min value inclusive and high value exclusive
min(int_language_score)

np.int64(1)

In [41]:
#high value inclusive and high value exclusive
max(int_language_score)

np.int64(99)

In [42]:
#Adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,51
1,female,group C,some college,standard,completed,69,90,88,33
2,female,group B,master's degree,standard,none,90,95,93,94
3,male,group A,associate's degree,free/reduced,none,47,57,44,6
4,male,group C,some college,standard,none,76,78,75,99

In [43]:
#Create random float numbers between 1 and 100
np.random.uniform(1, 100, size=100)

array([22.30465818, 75.20979237, 88.25353879, 82.0477506 , 21.3802901 ,
       42.8250835 , 30.75129312,  7.45083493, 37.87062108, 43.95436648,
       93.75550803, 62.41384606, 20.77005211, 20.06939603, 26.31877956,
       35.2064666 ,  1.92542538, 91.6389166 , 36.2369293 , 48.41998198,
       82.06757795, 83.15881147, 88.8275188 , 95.12535347, 57.37503896,
       46.43073381,  4.44491554, 29.13150985, 55.24867002, 89.38935506,
       29.58127494, 47.3573597 , 66.58046271, 60.39198898, 13.97156142,
       53.0634544 , 16.12613672, 51.04647868, 28.10540631,  1.38042008,
        8.67508616, 18.9405239 , 34.46025213, 44.92162763, 30.62131626,
       34.35132256, 61.99446753, 87.69294617, 60.78608578, 89.97241538,
       61.81842895, 69.8003275 , 48.97756387, 77.95661044, 23.08640411,
       98.03752146,  4.66683895, 76.79906675, 46.06423292, 46.98168532,
        7.80498507, 57.94557831, 13.57600798, 60.25350856, 76.2022649 ,
       38.11898706, 98.8828815 , 55.85989408, 74.55846096, 78.66793128,
       58.91766551, 59.83442877, 22.26615241, 33.34979996, 28.49320484,
       49.40556533, 49.96071882, 91.74208991, 56.85441019, 90.67092481,
       14.39569768,  4.72974847, 67.60469254, 79.40076045, 87.74758324,
       97.95226706, 75.85346565, 25.07352638, 31.41879332, 36.79433382,
       79.58681329, 80.38745827, 79.53089578, 89.82965572, 29.90024661,
       54.09716269, 86.18406533, 27.81943572, 20.45241084, 19.23733593])

assing()

When to use assing?

    -> Add multiple columns in a single line of code
    -> When you need to overwrite the values of an existing columns (best practice)

It returns a new object (a copy) with all the original columns in addition to the new ones

In [44]:
#Create random numbers for our new score columns
score_1 = np.random.randint(1,100, size=1000)
score_2 = np.random.randint(1,100, size=1000)

In [45]:
#Create a series using the random numbers
series_1 = pd.Series(score_1, index=np.arange(0, 1000))
series_2 = pd.Series(score_2, index=np.arange(0, 1000))

In [49]:
#Using assign() to add multiple columns
df_exams = df_exams.assign(score_1= series_1,score_2 = series_2)
df_exams.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2
0,female,group B,bachelor's degree,standard,none,72,72,74,51,67,86
1,female,group C,some college,standard,completed,69,90,88,33,5,7
2,female,group B,master's degree,standard,none,90,95,93,94,88,92

isert()

Inserts a new column at a specific position or index

In [51]:
#Using index() to add a column at a specific position
df_exams.insert(1, 'test', series_1) #(número do índice, nome da coluna, valor da coluna)
df_exams.head(3)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2
0,female,67,group B,bachelor's degree,standard,none,72,72,74,51,67,86
1,female,5,group C,some college,standard,completed,69,90,88,33,5,7
2,female,88,group B,master's degree,standard,none,90,95,93,94,88,92

###Math operations

####Operations in columns

In [52]:
#Select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [ ]:
#count, mean, std, max, and min of a column
df_exams['math score'].count()

np.int64(1000)

In [54]:
df_exams['math score'].mean()

np.float64(66.089)

In [55]:
df_exams['math score'].std()

15.163080096009468

In [56]:
df_exams['math score'].max()

100

In [57]:
df_exams['math score'].min()

0

In [58]:
#easier calculation with .describbe()
df_exams.describe()

,test,math score,reading score,writing score,language score,score_1,score_2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,50.169000,66.08900,69.169000,68.054000,50.247000,50.169000,49.048000
std,29.028281,15.16308,14.600192,15.195657,28.230639,29.028281,28.196822
min,1.000000,0.00000,17.000000,10.000000,1.000000,1.000000,1.000000
25%,23.000000,57.00000,59.000000,57.750000,26.000000,23.000000,23.000000
50%,51.000000,66.00000,70.000000,69.000000,50.500000,51.000000,49.000000
75%,74.250000,77.00000,79.000000,79.000000,74.000000,74.250000,74.000000
max,99.000000,100.00000,100.000000,100.000000,99.000000,99.000000,99.000000

####Operation in rows

In [67]:
#Calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [64]:
#Calculating the average score and assinging the result to a new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3
df_exams.head(3).round(2)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
0,female,67,group B,bachelor's degree,standard,none,72,72,74,51,67,86,72.67
1,female,5,group C,some college,standard,completed,69,90,88,33,5,7,82.33
2,female,88,group B,master's degree,standard,none,90,95,93,94,88,92,92.67

###Value counts

In [69]:
#Counting gender elements

#len function
len(df_exams['gender'])

#.count() method
df_exams['gender'].count()

np.int64(1000)

In [70]:
#Counting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [71]:
#return the relative frequencyy (divide all values by the sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [72]:
#Counting 'parental level of education' elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [73]:
#return the relative frequencyy and round to 2 decimals
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

###Sort a dataframe